// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.176.0
//   protoc               unknown
// source: filter.proto

/* eslint-disable */
import _m0 from "protobufjs/minimal.js";
import { Address, B256 } from "./common.js";

export const protobufPackage = "evm.v2";

/** EVM DNA definitions (filter). */

export enum HeaderFilter {
  UNSPECIFIED = 0,
  ALWAYS = 1,
  ON_DATA = 2,
  ON_DATA_OR_ON_NEW_BLOCK = 3,
  UNRECOGNIZED = -1,
}

export function headerFilterFromJSON(object: any): HeaderFilter {
  switch (object) {
    case 0:
    case "HEADER_FILTER_UNSPECIFIED":
      return HeaderFilter.UNSPECIFIED;
    case 1:
    case "HEADER_FILTER_ALWAYS":
      return HeaderFilter.ALWAYS;
    case 2:
    case "HEADER_FILTER_ON_DATA":
      return HeaderFilter.ON_DATA;
    case 3:
    case "HEADER_FILTER_ON_DATA_OR_ON_NEW_BLOCK":
      return HeaderFilter.ON_DATA_OR_ON_NEW_BLOCK;
    case -1:
    case "UNRECOGNIZED":
    default:
      return HeaderFilter.UNRECOGNIZED;
  }
}

export function headerFilterToJSON(object: HeaderFilter): string {
  switch (object) {
    case HeaderFilter.UNSPECIFIED:
      return "HEADER_FILTER_UNSPECIFIED";
    case HeaderFilter.ALWAYS:
      return "HEADER_FILTER_ALWAYS";
    case HeaderFilter.ON_DATA:
      return "HEADER_FILTER_ON_DATA";
    case HeaderFilter.ON_DATA_OR_ON_NEW_BLOCK:
      return "HEADER_FILTER_ON_DATA_OR_ON_NEW_BLOCK";
    case HeaderFilter.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum TransactionStatusFilter {
  UNSPECIFIED = 0,
  SUCCEEDED = 1,
  REVERTED = 2,
  ALL = 3,
  UNRECOGNIZED = -1,
}

export function transactionStatusFilterFromJSON(object: any): TransactionStatusFilter {
  switch (object) {
    case 0:
    case "TRANSACTION_STATUS_FILTER_UNSPECIFIED":
      return TransactionStatusFilter.UNSPECIFIED;
    case 1:
    case "TRANSACTION_STATUS_FILTER_SUCCEEDED":
      return TransactionStatusFilter.SUCCEEDED;
    case 2:
    case "TRANSACTION_STATUS_FILTER_REVERTED":
      return TransactionStatusFilter.REVERTED;
    case 3:
    case "TRANSACTION_STATUS_FILTER_ALL":
      return TransactionStatusFilter.ALL;
    case -1:
    case "UNRECOGNIZED":
    default:
      return TransactionStatusFilter.UNRECOGNIZED;
  }
}

export function transactionStatusFilterToJSON(object: TransactionStatusFilter): string {
  switch (object) {
    case TransactionStatusFilter.UNSPECIFIED:
      return "TRANSACTION_STATUS_FILTER_UNSPECIFIED";
    case TransactionStatusFilter.SUCCEEDED:
      return "TRANSACTION_STATUS_FILTER_SUCCEEDED";
    case TransactionStatusFilter.REVERTED:
      return "TRANSACTION_STATUS_FILTER_REVERTED";
    case TransactionStatusFilter.ALL:
      return "TRANSACTION_STATUS_FILTER_ALL";
    case TransactionStatusFilter.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface Filter {
  /** Include header. */
  readonly header?:
    | HeaderFilter
    | undefined;
  /** Filter withdrawals. */
  readonly withdrawals?:
    | readonly WithdrawalFilter[]
    | undefined;
  /** Filter transactions. */
  readonly transactions?:
    | readonly TransactionFilter[]
    | undefined;
  /** Filter logs. */
  readonly logs?: readonly LogFilter[] | undefined;
}

export interface WithdrawalFilter {
  readonly id?:
    | number
    | undefined;
  /** Filter based on the validator index. */
  readonly validatorIndex?:
    | number
    | undefined;
  /** Filter based on the withdrawal's target address. */
  readonly address?: Address | undefined;
}

export interface TransactionFilter {
  readonly id?:
    | number
    | undefined;
  /** Filter based on the transaction's sender address. */
  readonly from?:
    | Address
    | undefined;
  /** Filter based on the transaction's recipient address. */
  readonly to?:
    | Address
    | undefined;
  /** / Only return `create` transactions. Defaults to `false`. */
  readonly create?:
    | boolean
    | undefined;
  /**
   * Filter based on the transaction status.
   *
   * Defaults to `Succeeded`.
   */
  readonly transactionStatus?:
    | TransactionStatusFilter
    | undefined;
  /** Flag to request the transaction's receipt. Defaults to `false`. */
  readonly includeReceipt?:
    | boolean
    | undefined;
  /** Flag to request the transaction's logs. Defaults to `false`. */
  readonly includeLogs?:
    | boolean
    | undefined;
  /** Flag to request the transaction's trace. Defaults to `false`. */
  readonly includeTransactionTrace?: boolean | undefined;
}

export interface LogFilter {
  readonly id?:
    | number
    | undefined;
  /** Filter based on the log's contract address. */
  readonly address?:
    | Address
    | undefined;
  /** Filter based on the log's topics. */
  readonly topics?:
    | readonly Topic[]
    | undefined;
  /**
   * Only returns logs with topics of exactly the same length as the filter.
   *
   * Defaults to `false`.
   */
  readonly strict?:
    | boolean
    | undefined;
  /**
   * Filter based on the transaction status.
   *
   * Defaults to `Succeeded`.
   */
  readonly transactionStatus?:
    | TransactionStatusFilter
    | undefined;
  /** Flag to request the log's transaction. Defaults to `false`. */
  readonly includeTransaction?:
    | boolean
    | undefined;
  /** Flag to request the log's receipt. Defaults to `false`. */
  readonly includeReceipt?:
    | boolean
    | undefined;
  /**
   * Include sibling logs, that is logs emitted by the same transaction.
   *
   * Defaults to false.
   */
  readonly includeSiblings?:
    | boolean
    | undefined;
  /** Flag to request the log's trace. Defaults to `false`. */
  readonly includeTransactionTrace?: boolean | undefined;
}

/** Topic filter. */
export interface Topic {
  /** Topic value. Leave empty to match any topic. */
  readonly value?: B256 | undefined;
}

function createBaseFilter(): Filter {
  return { header: 0, withdrawals: [], transactions: [], logs: [] };
}

export const Filter = {
  encode(message: Filter, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.header !== undefined && message.header !== 0) {
      writer.uint32(8).int32(message.header);
    }
    if (message.withdrawals !== undefined && message.withdrawals.length !== 0) {
      for (const v of message.withdrawals) {
        WithdrawalFilter.encode(v!, writer.uint32(18).fork()).ldelim();
      }
    }
    if (message.transactions !== undefined && message.transactions.length !== 0) {
      for (const v of message.transactions) {
        TransactionFilter.encode(v!, writer.uint32(26).fork()).ldelim();
      }
    }
    if (message.logs !== undefined && message.logs.length !== 0) {
      for (const v of message.logs) {
        LogFilter.encode(v!, writer.uint32(34).fork()).ldelim();
      }
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Filter {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFilter() as any;
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.header = reader.int32() as any;
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.withdrawals!.push(WithdrawalFilter.decode(reader, reader.uint32()));
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.transactions!.push(TransactionFilter.decode(reader, reader.uint32()));
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.logs!.push(LogFilter.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Filter {
    return {
      header: isSet(object.header) ? headerFilterFromJSON(object.header) : 0,
      withdrawals: globalThis.Array.isArray(object?.withdrawals)
        ? object.withdrawals.map((e: any) => WithdrawalFilter.fromJSON(e))
        : [],
      transactions: globalThis.Array.isArray(object?.transactions)
        ? object.transactions.map((e: any) => TransactionFilter.fromJSON(e))
        : [],
      logs: globalThis.Array.isArray(object?.logs) ? object.logs.map((e: any) => LogFilter.fromJSON(e)) : [],
    };
  },

  toJSON(message: Filter): unknown {
    const obj: any = {};
    if (message.header !== undefined && message.header !== 0) {
      obj.header = headerFilterToJSON(message.header);
    }
    if (message.withdrawals?.length) {
      obj.withdrawals = message.withdrawals.map((e) => WithdrawalFilter.toJSON(e));
    }
    if (message.transactions?.length) {
      obj.transactions = message.transactions.map((e) => TransactionFilter.toJSON(e));
    }
    if (message.logs?.length) {
      obj.logs = message.logs.map((e) => LogFilter.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<Filter>): Filter {
    return Filter.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Filter>): Filter {
    const message = createBaseFilter() as any;
    message.header = object.header ?? 0;
    message.withdrawals = object.withdrawals?.map((e) => WithdrawalFilter.fromPartial(e)) || [];
    message.transactions = object.transactions?.map((e) => TransactionFilter.fromPartial(e)) || [];
    message.logs = object.logs?.map((e) => LogFilter.fromPartial(e)) || [];
    return message;
  },
};

function createBaseWithdrawalFilter(): WithdrawalFilter {
  return { id: 0, validatorIndex: undefined, address: undefined };
}

export const WithdrawalFilter = {
  encode(message: WithdrawalFilter, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.id !== undefined && message.id !== 0) {
      writer.uint32(8).uint32(message.id);
    }
    if (message.validatorIndex !== undefined) {
      writer.uint32(16).uint32(message.validatorIndex);
    }
    if (message.address !== undefined) {
      Address.encode(message.address, writer.uint32(26).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): WithdrawalFilter {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWithdrawalFilter() as any;
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.id = reader.uint32();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.validatorIndex = reader.uint32();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.address = Address.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): WithdrawalFilter {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      validatorIndex: isSet(object.validatorIndex) ? globalThis.Number(object.validatorIndex) : undefined,
      address: isSet(object.address) ? Address.fromJSON(object.address) : undefined,
    };
  },

  toJSON(message: WithdrawalFilter): unknown {
    const obj: any = {};
    if (message.id !== undefined && message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.validatorIndex !== undefined) {
      obj.validatorIndex = Math.round(message.validatorIndex);
    }
    if (message.address !== undefined) {
      obj.address = Address.toJSON(message.address);
    }
    return obj;
  },

  create(base?: DeepPartial<WithdrawalFilter>): WithdrawalFilter {
    return WithdrawalFilter.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<WithdrawalFilter>): WithdrawalFilter {
    const message = createBaseWithdrawalFilter() as any;
    message.id = object.id ?? 0;
    message.validatorIndex = object.validatorIndex ?? undefined;
    message.address = (object.address !== undefined && object.address !== null)
      ? Address.fromPartial(object.address)
      : undefined;
    return message;
  },
};

function createBaseTransactionFilter(): TransactionFilter {
  return {
    id: 0,
    from: undefined,
    to: undefined,
    create: undefined,
    transactionStatus: undefined,
    includeReceipt: undefined,
    includeLogs: undefined,
    includeTransactionTrace: undefined,
  };
}

export const TransactionFilter = {
  encode(message: TransactionFilter, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.id !== undefined && message.id !== 0) {
      writer.uint32(8).uint32(message.id);
    }
    if (message.from !== undefined) {
      Address.encode(message.from, writer.uint32(18).fork()).ldelim();
    }
    if (message.to !== undefined) {
      Address.encode(message.to, writer.uint32(26).fork()).ldelim();
    }
    if (message.create !== undefined) {
      writer.uint32(32).bool(message.create);
    }
    if (message.transactionStatus !== undefined) {
      writer.uint32(40).int32(message.transactionStatus);
    }
    if (message.includeReceipt !== undefined) {
      writer.uint32(48).bool(message.includeReceipt);
    }
    if (message.includeLogs !== undefined) {
      writer.uint32(56).bool(message.includeLogs);
    }
    if (message.includeTransactionTrace !== undefined) {
      writer.uint32(64).bool(message.includeTransactionTrace);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): TransactionFilter {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTransactionFilter() as any;
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.id = reader.uint32();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.from = Address.decode(reader, reader.uint32());
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.to = Address.decode(reader, reader.uint32());
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.create = reader.bool();
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.transactionStatus = reader.int32() as any;
          continue;
        case 6:
          if (tag !== 48) {
            break;
          }

          message.includeReceipt = reader.bool();
          continue;
        case 7:
          if (tag !== 56) {
            break;
          }

          message.includeLogs = reader.bool();
          continue;
        case 8:
          if (tag !== 64) {
            break;
          }

          message.includeTransactionTrace = reader.bool();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TransactionFilter {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      from: isSet(object.from) ? Address.fromJSON(object.from) : undefined,
      to: isSet(object.to) ? Address.fromJSON(object.to) : undefined,
      create: isSet(object.create) ? globalThis.Boolean(object.create) : undefined,
      transactionStatus: isSet(object.transactionStatus)
        ? transactionStatusFilterFromJSON(object.transactionStatus)
        : undefined,
      includeReceipt: isSet(object.includeReceipt) ? globalThis.Boolean(object.includeReceipt) : undefined,
      includeLogs: isSet(object.includeLogs) ? globalThis.Boolean(object.includeLogs) : undefined,
      includeTransactionTrace: isSet(object.includeTransactionTrace)
        ? globalThis.Boolean(object.includeTransactionTrace)
        : undefined,
    };
  },

  toJSON(message: TransactionFilter): unknown {
    const obj: any = {};
    if (message.id !== undefined && message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.from !== undefined) {
      obj.from = Address.toJSON(message.from);
    }
    if (message.to !== undefined) {
      obj.to = Address.toJSON(message.to);
    }
    if (message.create !== undefined) {
      obj.create = message.create;
    }
    if (message.transactionStatus !== undefined) {
      obj.transactionStatus = transactionStatusFilterToJSON(message.transactionStatus);
    }
    if (message.includeReceipt !== undefined) {
      obj.includeReceipt = message.includeReceipt;
    }
    if (message.includeLogs !== undefined) {
      obj.includeLogs = message.includeLogs;
    }
    if (message.includeTransactionTrace !== undefined) {
      obj.includeTransactionTrace = message.includeTransactionTrace;
    }
    return obj;
  },

  create(base?: DeepPartial<TransactionFilter>): TransactionFilter {
    return TransactionFilter.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<TransactionFilter>): TransactionFilter {
    const message = createBaseTransactionFilter() as any;
    message.id = object.id ?? 0;
    message.from = (object.from !== undefined && object.from !== null) ? Address.fromPartial(object.from) : undefined;
    message.to = (object.to !== undefined && object.to !== null) ? Address.fromPartial(object.to) : undefined;
    message.create = object.create ?? undefined;
    message.transactionStatus = object.transactionStatus ?? undefined;
    message.includeReceipt = object.includeReceipt ?? undefined;
    message.includeLogs = object.includeLogs ?? undefined;
    message.includeTransactionTrace = object.includeTransactionTrace ?? undefined;
    return message;
  },
};

function createBaseLogFilter(): LogFilter {
  return {
    id: 0,
    address: undefined,
    topics: [],
    strict: undefined,
    transactionStatus: undefined,
    includeTransaction: undefined,
    includeReceipt: undefined,
    includeSiblings: undefined,
    includeTransactionTrace: undefined,
  };
}

export const LogFilter = {
  encode(message: LogFilter, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.id !== undefined && message.id !== 0) {
      writer.uint32(8).uint32(message.id);
    }
    if (message.address !== undefined) {
      Address.encode(message.address, writer.uint32(18).fork()).ldelim();
    }
    if (message.topics !== undefined && message.topics.length !== 0) {
      for (const v of message.topics) {
        Topic.encode(v!, writer.uint32(26).fork()).ldelim();
      }
    }
    if (message.strict !== undefined) {
      writer.uint32(32).bool(message.strict);
    }
    if (message.transactionStatus !== undefined) {
      writer.uint32(40).int32(message.transactionStatus);
    }
    if (message.includeTransaction !== undefined) {
      writer.uint32(48).bool(message.includeTransaction);
    }
    if (message.includeReceipt !== undefined) {
      writer.uint32(56).bool(message.includeReceipt);
    }
    if (message.includeSiblings !== undefined) {
      writer.uint32(64).bool(message.includeSiblings);
    }
    if (message.includeTransactionTrace !== undefined) {
      writer.uint32(72).bool(message.includeTransactionTrace);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): LogFilter {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLogFilter() as any;
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.id = reader.uint32();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.address = Address.decode(reader, reader.uint32());
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.topics!.push(Topic.decode(reader, reader.uint32()));
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.strict = reader.bool();
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.transactionStatus = reader.int32() as any;
          continue;
        case 6:
          if (tag !== 48) {
            break;
          }

          message.includeTransaction = reader.bool();
          continue;
        case 7:
          if (tag !== 56) {
            break;
          }

          message.includeReceipt = reader.bool();
          continue;
        case 8:
          if (tag !== 64) {
            break;
          }

          message.includeSiblings = reader.bool();
          continue;
        case 9:
          if (tag !== 72) {
            break;
          }

          message.includeTransactionTrace = reader.bool();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LogFilter {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      address: isSet(object.address) ? Address.fromJSON(object.address) : undefined,
      topics: globalThis.Array.isArray(object?.topics) ? object.topics.map((e: any) => Topic.fromJSON(e)) : [],
      strict: isSet(object.strict) ? globalThis.Boolean(object.strict) : undefined,
      transactionStatus: isSet(object.transactionStatus)
        ? transactionStatusFilterFromJSON(object.transactionStatus)
        : undefined,
      includeTransaction: isSet(object.includeTransaction) ? globalThis.Boolean(object.includeTransaction) : undefined,
      includeReceipt: isSet(object.includeReceipt) ? globalThis.Boolean(object.includeReceipt) : undefined,
      includeSiblings: isSet(object.includeSiblings) ? globalThis.Boolean(object.includeSiblings) : undefined,
      includeTransactionTrace: isSet(object.includeTransactionTrace)
        ? globalThis.Boolean(object.includeTransactionTrace)
        : undefined,
    };
  },

  toJSON(message: LogFilter): unknown {
    const obj: any = {};
    if (message.id !== undefined && message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.address !== undefined) {
      obj.address = Address.toJSON(message.address);
    }
    if (message.topics?.length) {
      obj.topics = message.topics.map((e) => Topic.toJSON(e));
    }
    if (message.strict !== undefined) {
      obj.strict = message.strict;
    }
    if (message.transactionStatus !== undefined) {
      obj.transactionStatus = transactionStatusFilterToJSON(message.transactionStatus);
    }
    if (message.includeTransaction !== undefined) {
      obj.includeTransaction = message.includeTransaction;
    }
    if (message.includeReceipt !== undefined) {
      obj.includeReceipt = message.includeReceipt;
    }
    if (message.includeSiblings !== undefined) {
      obj.includeSiblings = message.includeSiblings;
    }
    if (message.includeTransactionTrace !== undefined) {
      obj.includeTransactionTrace = message.includeTransactionTrace;
    }
    return obj;
  },

  create(base?: DeepPartial<LogFilter>): LogFilter {
    return LogFilter.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<LogFilter>): LogFilter {
    const message = createBaseLogFilter() as any;
    message.id = object.id ?? 0;
    message.address = (object.address !== undefined && object.address !== null)
      ? Address.fromPartial(object.address)
      : undefined;
    message.topics = object.topics?.map((e) => Topic.fromPartial(e)) || [];
    message.strict = object.strict ?? undefined;
    message.transactionStatus = object.transactionStatus ?? undefined;
    message.includeTransaction = object.includeTransaction ?? undefined;
    message.includeReceipt = object.includeReceipt ?? undefined;
    message.includeSiblings = object.includeSiblings ?? undefined;
    message.includeTransactionTrace = object.includeTransactionTrace ?? undefined;
    return message;
  },
};

function createBaseTopic(): Topic {
  return { value: undefined };
}

export const Topic = {
  encode(message: Topic, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.value !== undefined) {
      B256.encode(message.value, writer.uint32(10).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Topic {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTopic() as any;
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.value = B256.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Topic {
    return { value: isSet(object.value) ? B256.fromJSON(object.value) : undefined };
  },

  toJSON(message: Topic): unknown {
    const obj: any = {};
    if (message.value !== undefined) {
      obj.value = B256.toJSON(message.value);
    }
    return obj;
  },

  create(base?: DeepPartial<Topic>): Topic {
    return Topic.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Topic>): Topic {
    const message = createBaseTopic() as any;
    message.value = (object.value !== undefined && object.value !== null) ? B256.fromPartial(object.value) : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | bigint | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { readonly $case: string }
    ? { [K in keyof Omit<T, "$case">]?: DeepPartial<T[K]> } & { readonly $case: T["$case"] }
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
