export const ENV_INTERNAL_APIBARA_RUNTIME = "_APIBARA_RUNTIME";
export const ENV_INTERNAL_APIBARA_PRESET = "_APIBARA_PRESET";
export const ENV_INTERNAL_APIBARA_PRESETS = "_APIBARA_PRESETS";
export const ENV_INTERNAL_APIBARA_PROCESSED_RUNTIME =
  "_APIBARA_PROCESSED_RUNTIME";
export const USER_ENV_APIBARA_RUNTIME_CONFIG = "APIBARA_RUNTIME_CONFIG";
