// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.176.0
//   protoc               unknown
// source: common.proto

/* eslint-disable */
import Long from "long";
import _m0 from "protobufjs/minimal";

export const protobufPackage = "starknet.v2";

/** A field element. */
export interface FieldElement {
  readonly loLo?: bigint | undefined;
  readonly loHi?: bigint | undefined;
  readonly hiLo?: bigint | undefined;
  readonly hiHi?: bigint | undefined;
}

function createBaseFieldElement(): FieldElement {
  return { loLo: BigInt("0"), loHi: BigInt("0"), hiLo: BigInt("0"), hiHi: BigInt("0") };
}

export const FieldElement = {
  encode(message: FieldElement, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.loLo !== undefined && message.loLo !== BigInt("0")) {
      if (BigInt.asUintN(64, message.loLo) !== message.loLo) {
        throw new globalThis.Error("value provided for field message.loLo of type fixed64 too large");
      }
      writer.uint32(9).fixed64(message.loLo.toString());
    }
    if (message.loHi !== undefined && message.loHi !== BigInt("0")) {
      if (BigInt.asUintN(64, message.loHi) !== message.loHi) {
        throw new globalThis.Error("value provided for field message.loHi of type fixed64 too large");
      }
      writer.uint32(17).fixed64(message.loHi.toString());
    }
    if (message.hiLo !== undefined && message.hiLo !== BigInt("0")) {
      if (BigInt.asUintN(64, message.hiLo) !== message.hiLo) {
        throw new globalThis.Error("value provided for field message.hiLo of type fixed64 too large");
      }
      writer.uint32(25).fixed64(message.hiLo.toString());
    }
    if (message.hiHi !== undefined && message.hiHi !== BigInt("0")) {
      if (BigInt.asUintN(64, message.hiHi) !== message.hiHi) {
        throw new globalThis.Error("value provided for field message.hiHi of type fixed64 too large");
      }
      writer.uint32(33).fixed64(message.hiHi.toString());
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): FieldElement {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFieldElement() as any;
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 9) {
            break;
          }

          message.loLo = longToBigint(reader.fixed64() as Long);
          continue;
        case 2:
          if (tag !== 17) {
            break;
          }

          message.loHi = longToBigint(reader.fixed64() as Long);
          continue;
        case 3:
          if (tag !== 25) {
            break;
          }

          message.hiLo = longToBigint(reader.fixed64() as Long);
          continue;
        case 4:
          if (tag !== 33) {
            break;
          }

          message.hiHi = longToBigint(reader.fixed64() as Long);
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FieldElement {
    return {
      loLo: isSet(object.loLo) ? BigInt(object.loLo) : BigInt("0"),
      loHi: isSet(object.loHi) ? BigInt(object.loHi) : BigInt("0"),
      hiLo: isSet(object.hiLo) ? BigInt(object.hiLo) : BigInt("0"),
      hiHi: isSet(object.hiHi) ? BigInt(object.hiHi) : BigInt("0"),
    };
  },

  toJSON(message: FieldElement): unknown {
    const obj: any = {};
    if (message.loLo !== undefined && message.loLo !== BigInt("0")) {
      obj.loLo = message.loLo.toString();
    }
    if (message.loHi !== undefined && message.loHi !== BigInt("0")) {
      obj.loHi = message.loHi.toString();
    }
    if (message.hiLo !== undefined && message.hiLo !== BigInt("0")) {
      obj.hiLo = message.hiLo.toString();
    }
    if (message.hiHi !== undefined && message.hiHi !== BigInt("0")) {
      obj.hiHi = message.hiHi.toString();
    }
    return obj;
  },

  create(base?: DeepPartial<FieldElement>): FieldElement {
    return FieldElement.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<FieldElement>): FieldElement {
    const message = createBaseFieldElement() as any;
    message.loLo = object.loLo ?? BigInt("0");
    message.loHi = object.loHi ?? BigInt("0");
    message.hiLo = object.hiLo ?? BigInt("0");
    message.hiHi = object.hiHi ?? BigInt("0");
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | bigint | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { readonly $case: string }
    ? { [K in keyof Omit<T, "$case">]?: DeepPartial<T[K]> } & { readonly $case: T["$case"] }
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function longToBigint(long: Long) {
  return BigInt(long.toString());
}

if (_m0.util.Long !== Long) {
  _m0.util.Long = Long as any;
  _m0.configure();
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
