{
 "title": "Indexer Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Current Block",
   "type": "stat",
   "gridPos": { "h": 12, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Block" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "current_block", "legendFormat": "Current Block" }
   ]
  },
  {
   "title": "Reorg Count",
   "type": "stat",
   "gridPos": { "h": 12, "w": 8, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Reorgs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "reorg_count_total", "legendFormat": "Reorgs" }
   ]
  },
  {
   "title": "Processed Blocks",
   "type": "stat",
   "gridPos": { "h": 12, "w": 8, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Blocks" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "processed_block_count_total", "legendFormat": "Processed Blocks" }
   ]
  }
 ]
}